function About() {
    return (<div>
        <h2>Sobre Mi</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum impedit soluta dolores deserunt assumenda, enim aliquam modi, earum illum nemo quibusdam autem tempore esse nesciunt, fugit consequuntur laboriosam iste distinctio dicta quas! Quo dolores a deserunt corrupti sint recusandae atque alias, tenetur suscipit magni vitae harum asperiores nostrum, officia, nulla aliquid voluptates consequuntur in repudiandae cupiditate veritatis beatae nemo eligendi quibusdam. Dolorum maiores odit magnam doloribus, ex explicabo unde fugiat optio recusandae sint, tenetur velit, rerum illum! Maxime sequi blanditiis ratione inventore voluptatibus nostrum, autem, ipsa excepturi praesentium ducimus vero! Consectetur dolorem nulla amet maiores fuga nobis aut neque numquam.</p>
        <hr />
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate recusandae quidem quam temporibus exercitationem maiores minus necessitatibus perferendis ex inventore consequatur tempora excepturi hic cupiditate doloremque possimus, assumenda praesentium magnam pariatur expedita eligendi porro similique officiis! Ab recusandae alias tenetur obcaecati quibusdam consectetur harum, cum maiores vero officia laudantium iusto eaque eos totam earum suscipit pariatur tempore ex excepturi nulla beatae? Labore, velit repellat? Neque, amet fuga nesciunt ipsam optio unde fugiat porro corporis? Fugiat, laudantium tempore necessitatibus id ea animi saepe, tempora veniam, eligendi deleniti minima ex quia nesciunt est amet atque quae aliquid ullam? Impedit ducimus alias ratione?</p>
        <br />
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quos, aliquid hic ipsa consequuntur at magnam nostrum temporibus iusto nisi recusandae, illo quae! Consectetur explicabo odio adipisci rem in eius expedita delectus nihil libero aut? Laudantium corporis praesentium qui voluptas ipsa doloremque perferendis ipsam molestiae. Possimus est sequi nisi, in unde aspernatur similique magnam tempora atque repellat numquam fugit voluptatum ullam nulla inventore provident, maxime tempore iusto expedita ipsum illo? Deserunt veritatis vitae id, dolorum odit eveniet sunt voluptates minima aliquid dolores aliquam voluptatum veniam earum rerum asperiores iure inventore! Deleniti culpa suscipit perferendis animi magnam iusto, placeat ab non!</p>
    </div>)
}

export default About;